### ISSUE TITLE
Implement missing transformers

### ISSUE THREAD

**Issue by ForbesLindesay** [jstransformers/jstransformer#1]
This project aims to replace [transformers](https://github.com/ForbesLindesay/transformers) with a large collection of separate libraries, each of which able to be separately maintained, tested and updated.  Each library will implement some subset of the API in this module, and may optionally return a string body rather than the `{body: String, dependencies: Array.<String>}` format (lots of file formats don't actually have dependencies so it wouldn't really make sense).  This module can then be used to fully normalise that interface, including implementing the methods that are otherwise not implemented.

Here is a list of all the modules that need implementing

- [x] [coffeecup](https://github.com/gradus/coffeecup)
- [x] [coffeekup](https://github.com/mauricemach/coffeekup)
- [x] [haml-coffee](https://github.com/netzpirat/haml-coffee/)
- [x] [jazz](https://github.com/shinetech/jazz)
- [ ] ~~[jqtpl](https://github.com/kof/jqtpl)~~
- [x] [just](https://github.com/baryshev/just)
- [x] [mote](https://github.com/satchmorun/mote)
- [x] [qejs](https://github.com/jepso/QEJS)
- [x] [templayed](https://github.com/archan937/templayed.js/)
- [x] [walrus](https://github.com/jeremyruppel/walrus)
- [x] [whiskers](https://github.com/gsf/whiskers.js)
- [x] [atpl](https://github.com/soywiz/atpl.js)
- [x] [dot](https://github.com/olado/doT)
- [x] [dust](https://github.com/akdubya/dustjs)
- [x] [haml](https://github.com/creationix/haml-js/)
- [x] [handlebars](https://github.com/wycats/handlebars.js)
- [x] [liquor](https://github.com/chjj/liquor) -- done but unusable and not published because of chjj/liquor#5
- [x] [markdown-js](https://github.com/evilstreak/markdown-js)
- [x] [toffee](https://github.com/malgorithms/toffee)
- [x] cdata
- [x] cdata-css
- [x] cdata-js
- [x] coffee-script
- [x] cson
- [x] eco
- [x] ect
- [x] ejs
- [x] escape-html
- [x] highlight.js
- [x] hogan
- [x] jade
- [x] less
- [x] livescript
- [x] markdown
- [x] markdown-it
- [x] marked
- [x] mustache
- [x] plates
- [x] remarkable
- [x] sass
- [x] scss
- [x] stylus
- [x] supermarked
- [x] swig
- [x] uglify-css -> rename this to "clean-css" and use the [clean-css](https://www.npmjs.com/package/clean-css) module
- [x] uglify-js
- [x] uglify-json -> rename this to just "json"
- [x] underscore
- [x] verbatim

### Potential Extras
- [x] [JsRender](https://github.com/borismoore/jsrender)
- [x] [Marko](https://github.com/raptorjs/marko)
- [ ] [CSS Longhand](https://github.com/hemanth/css-longhand)
- [x] [autoprefixer](https://github.com/postcss/autoprefixer-core) built with postcss
- [ ] [coffee-stylesheets](https://github.com/mikesmullin/coffee-stylesheets)
- [ ] [cssnext](https://github.com/cssnext/cssnext) built with postcss
- [ ] [doiuse](https://github.com/anandthakker/doiuse) built with postcss
- [ ] [fest](https://github.com/mailru/fest) xml to html transformation
- [ ] [gaikan](https://github.com/Deathspike/gaikan)
- [ ] [hyperscript](https://github.com/dominictarr/hyperscript)
- [ ] [j140](https://github.com/tunnckoCore/j140)
- [x] [stylecow](https://github.com/stylecow/stylecow)
- [ ] [String-Template](https://www.npmjs.com/package/string-template)
- [x] Duo.js
- [ ] [Coffee React](https://github.com/jsdf/coffee-react)
- [x] [octet](https://github.com/tunnckoCore/octet)
- [ ] [renderkid](https://github.com/AriaMinaei/RenderKid)
- [ ] [rtlcss](https://github.com/MohammadYounes/rtlcss) built with postcss
- [ ] [slm-lang](https://github.com/slm-lang/slm) jade-like template engine for node and browser
- [x] [svgo](https://github.com/svg/svgo) Nodejs-based tool for optimizing SVG vector graphics files
- [ ] ~~[ccss](https://github.com/aeosynth/ccss)~~ bugs, need PRs there
- [ ] ~~[coffee-templates](https://github.com/mikesmullin/coffee-templates)~~ tricky shit, atm
- [x] [absurdjs](https://github.com/krasimir/absurd)
- [x] [babel](https://babeljs.io/)
- [x] [browserify](http://browserify.org/)
- [x] [es6-template-strings](https://github.com/medikoo/es6-template-strings)
- [x] [gray-matter](https://github.com/jonschlinkert/gray-matter)
- [x] [ini](https://github.com/isaacs/ini)
- [x] [jsx](https://www.npmjs.com/package/react-tools)
- [x] [lodash](https://github.com/lodash/lodash)
- [x] [mini-handlebars](https://github.com/mikesmullin/mini-handlebars)
- [x] [myth](https://github.com/segmentio/myth)
- [x] [postcss](https://github.com/postcss/postcss)
- [x] [resin](https://github.com/topcoat/resin) built with rework
- [x] [rework](https://github.com/reworkcss/rework)
- [x] [toml](https://github.com/toml-lang/toml)
- [x] [webpack](https://github.com/webpack/webpack)
- [x] [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js)
- [x] styl
- [x] ~~[jscss](https://github.com/AlexanderSelzer/jscss)~~ bugs, need PRs there

Once all of these have been implemented, we can switch jade to look for these rather than transformers.  I'll need as many collaborators as possible for this, so if you're willing to contribute a transformer, let me know and I'll add you to the organisation.  P.S. note that we add `jstransformer` to the keywords in package.json for all transformers, so they can be found at https://www.npmjs.com/browse/keyword/jstransformer

**Comment by ForbesLindesay** [comment]
@bloodyowl @enlore @hemanth @jbnicolai @jeromew @rlidwka @TimothyGu would any of you like to help out?

**Comment by hemanth** [comment]
Count me in :)

**Comment by ForbesLindesay** [comment]
Awesome, welcome aboard :)

Please make sure you add `forbeslindesay` as an owner if you publish any new jstransformers to npm.  I'll write a bot at some point to add all of the owners on GitHub as owners on npm :)

**Comment by jbnicolai** [comment]
I'm game as well ^^

> I'll write a bot at some point to add all of the owners on GitHub as owners on npm

Good call.

**Comment by hemanth** [comment]
@ForbesLindesay Here we go! Started with [jstransformer-handlebars](https://github.com/jstransformers/jstransformer-handlebars) (Made it looks as close as your code.)

**Comment by ForbesLindesay** [comment]
Looks good.  Just had a thought though:

For templating engines we should support two step compilation (i.e. compile then render).  I would suggest we support:

```js
exports.compile = function (str, options) {
  reutrn function (locals) { /* return resulting string */ };
};
// or
exports.compile = function (str, options) {
  reutrn {fn: function (locals) { /* return resulting string */ }, dependencies: [/* array of files */]};
};
```

We could the have `template.render` behave like the following by default:

```js
exports.render = function (str, options, locals) {
  var compiled = exports.compile(str, options);
  if (typeof compiled === 'function') return compiled(locals || options);
  else return {body: compiled.fn(locals || options), dependencies: compiled.dependencies};
};
```

I'll do `underscore` and then update this library to show what I mean.

**Comment by hemanth** [comment]
Yup, `compile` and `render` makes sense and they are convenient as well.

**Comment by TimothyGu** [comment]
@ForbesLindesay sure I can use some fun porting modules over.

**Comment by bloodyowl** [comment]
I'll try to find the time to do some of them

**Comment by TimothyGu** [comment]
@ForbesLindesay how about caching? Do we let the libraries handle caching or do we use a DIY one like in transformers?

**Comment by TimothyGu** [comment]
Jade transformer written. Function signatures look like this:

```js
compile(source, options);
compileClient(source, options);
render(source, options, locals);
```

If this is OK I'll go ahead and write the transformer for EJS too.

**Comment by ForbesLindesay** [comment]
Looking at what's actually in that repo.  It looks perfect.  i.e.

```js
compileFile(source, options);
compileFileClient(source, options);
```

**Comment by ForbesLindesay** [comment]
For caching: wherever possible we disable all caching.  The `dependencies` array is there so that it is easy for an application to tell when a file needs to be rebuilt.  If the user wants caching, they should use the `Transformer.compile` interfaces instead of the `Transformer.render` interfaces and then they can cache the result of that.

The only part that I'm not 100% sure on is whether we should do anything for dynamic caches like browserify supports where you avoid re-parsing all the files that haven't changed.  Currently my intention is not to do anything special for those unless someone asks for it.

**Comment by TimothyGu** [comment]
@ForbesLindesay sounds good.

**Comment by JosefJezek** [comment]
Please :sparkles: `markdown-it` :sparkles: - modern pluggable markdown parser

See https://www.npmjs.com/browse/keyword/markdown-it

**Comment by TimothyGu** [comment]
@JosefJezek TODO added.

Uglify-JS and JSON beautifier/uglifier ported.

**Comment by TimothyGu** [comment]
verbatim and cdata* are ported.

**Comment by hemanth** [comment]
@ForbesLindesay I have implemented few of them, but haven't published it yet, as you had mentioned earlier that add all of the owners on GitHub as owners on npm, should I go ahead a publish them or wait?

**Comment by TimothyGu** [comment]
@hemanth I already published the ones ported by me. We can change the owners after we publish anyway.

**Comment by TimothyGu** [comment]
@hemanth regarding @ForbesLindesay's suggestion of writing a bot that fetches GitHub owners and automatically add them to npm, it's technically not possible as npm login and GitHub login might be different (e.g. ForbesLindesay (GitHub) vs forbeslindesay (npm)). What we can do is add all of the owners to one repo (i.e. this one) and do something like this:

```sh
owners="`npm owner ls jstransformer | cut -d' ' -f1`"

for p in `curl -s 'https://api.github.com/orgs/jstransformers/repos' | sed -n 's/.*"name".*:.*"\(.*\)",/\1/pg'`; do
    for u in $owners; do
        npm owner add "$u" "$p"
    done
done
```

(Bash FTW)

**Comment by hemanth** [comment]
@TimothyGu Nice, we must also update the `package.json` with authors or have a common author say like `jstransformer`.

**Comment by TimothyGu** [comment]
@hemanth I would argue against that, as 1. `package.json` cannot have more than one **authors**, only maintainers, and 2. not everybody will necessarily be maintaining every module, and adding the person to `maintainers` would just be dubious.

**Comment by ForbesLindesay** [comment]
@TimothyGu I was thinking that we would maintain a file somewhere that listed all project owner's npm accounts.

@hemanth go ahead and publish them, but if possible please add me as an owner on npm via:

    npm owner add forbeslindesay

**Comment by hemanth** [comment]
@ForbesLindesay Done.

**Comment by TimothyGu** [comment]
@ForbesLindesay that's fine too, but the question is where.

**Comment by RobLoach** [comment]
https://github.com/RobLoach/jstransformer-markdown-it

**Comment by TimothyGu** [comment]
@RobLoach done. I've also invited you to our maintainer team, so you can now push to that repo.

**Comment by TimothyGu** [comment]
@JosefJezek Markdown It support has been added.

**Comment by JosefJezek** [comment]
Thank you @TimothyGu and @RobLoach :+1:

**Comment by RobLoach** [comment]
:sparkles: `eco` :sparkles: https://github.com/RobLoach/jstransformer-eco

**Comment by RobLoach** [comment]
:sparkles: `swig` :sparkles: https://github.com/RobLoach/jstransformer-swig

**Comment by hemanth** [comment]
@RobLoach I was about to publish `swig` heh heh.

**Comment by RobLoach** [comment]
:eyes:
:tongue:

**Comment by ForbesLindesay** [comment]
@RobLoach since you're clearly hooked, I've added you to the owners team :)

**Comment by RobLoach** [comment]
@ForbesLindesay Thanks! :+1: 

:sparkles: `mustache` :sparkles:  https://github.com/jstransformers/jstransformer-mustache

**Comment by RobLoach** [comment]
:sparkles: `plates` :sparkles: http://github.com/jstransformers/jstransformer-plates

**Comment by TimothyGu** [comment]
@RobLoach nice work! However, remember to enable Coveralls in addition to Travis CI so that the coverage badge works.

**Comment by RobLoach** [comment]
:sparkles: ect :sparkles: https://github.com/jstransformers/jstransformer-ect

**Comment by RobLoach** [comment]
:sparkles: `atpl` :sparkles: https://github.com/jstransformers/jstransformer-atpl

Also linked the template engines in Forbes original post so that they're easier to find.

**Comment by RobLoach** [comment]
:sparkles: `dot` :sparkles:  https://github.com/jstransformers/jstransformer-dot

**Comment by tunnckoCore** [comment]
count me in, i follow this org since you create it, lol
have some transformers in mind and can help with toffee, mote and coffeecup (there have newer impl [coffee-templates](https://github.com/mikesmullin/coffee-templates) and [mini-coffeecup](https://github.com/mikesmullin/mini-coffeecup), i think we can replace legacy 4years coffeecup with them around 2years inactivity, lol) beside that.. I'll rewrite them asap

**Comment by TimothyGu** [comment]
@tunnckoCore do you have anything implemented already? If so I can take over those modules right now.

**Comment by tunnckoCore** [comment]
atm nope, tonight. just see the issues and lots of new transformers in org and decide to comment immediately :)

**Comment by RobLoach** [comment]
[HyperScript](https://github.com/dominictarr/hyperscript) wouldn't make sense as a jstransformer, would it?

**Comment by TimothyGu** [comment]
@RobLoach It's just JavaScript. If you really think it would be helpful to do something like:

```jade
html
  body
    :hyperscript
      h('p', "why don't you just use Jade?")
```

, sure. (For me at least it's a waste of time.)

**Comment by RobLoach** [comment]
https://github.com/reworkcss/rework

**Comment by tunnckoCore** [comment]
@RobLoach exactly that I have in mind + postcss. on the road

**Comment by ForbesLindesay** [comment]
@tunnckoCore welcome to the team. I've added you as an owner and look forward to seeing what you produce :)

I've added rework and postcss to the list :)

**Comment by tunnckoCore** [comment]
@ForbesLindesay thanks! :)

> I've added rework and postcss to the list :)

I think we should name it just `jstransformer-css`? Im on them now and .. this is the Q.

**Comment by tunnckoCore** [comment]
:sparkles: rework :sparkles: transform CSS to JSON AST usin `reworkcss/css`

**Comment by tunnckoCore** [comment]
:sparkles: postcss :sparkles: transform CSS to JSON AST using `postcss.parse()`

**Comment by tunnckoCore** [comment]
:sparkles: myth :sparkles: done

**Comment by TimothyGu** [comment]
@tunnckoCore, I am not exactly satisfied with the quality of the new modules.

1. jstransformer-css has a very confusing name. It is impossible to tell that it is a CSS parser just from its name. Even though `css` is the name of the module I think it would make more sense if a more descriptive name is used.
2. Stuff like [this](https://github.com/jstransformers/jstransformer-css/commit/482580bece8723327d0e382753e3b09480754ffd#commitcomment-10557292)
3. Stuff like [this](https://github.com/jstransformers/jstransformer-css/blob/master/.coveralls.yml)
4. I also don't feel comfortable with https://github.com/jstransformers/jstransformer-postcss#author. That kind of destroys the unity of jstransfomers as an organization.

I would also suggest looking at the existing modules to get a feel on how everything works, to preserve some sense of unity among all the modules: https://github.com/jstransformers/jstransformer-jade/blob/master/package.json#L16-L20

I also do not think we should do things like:

```yaml
matrix:
  allow_failures:
    - node_js: "0.10"
```

or

```yaml
node_js:
  - 0.11
```

If we don't support 0.10 why test it at all? Plus nobody uses Node.js 0.11 (or at least nobody *encourages* using 0.11 now that 0.12 is out). Those are just plain useless.

Also, these files are also up for discussion:

- .editorconfig
- .gitattributes (which also contains stuff we would not EVER need like say rules for .mp3 files)
- .jshint*

**Comment by tunnckoCore** [comment]
1. its better to be than `jstransformer-reworkcss`
2. i cant understand whats the problem is. just describes that pkg is published as v0.1.1
3. always add it because I dont want in every change to go to the shitty coveralls.io website to regen it and get it and etc, and etc.

> If we don't support 0.10 why test it at all? Plus nobody uses Node.js 0.11 (or at least nobody encourages using 0.11 now that 0.12 is out). Those are just plain useless.

templates, templates, templates. I must change them soon. Also they are the reason for the author and etc stuff.  I just forgot that.

**Comment by TimothyGu** [comment]
> 1. its better to be than `jstransformer-reworkcss`

Have you considered `jstransformer-css-parse`?

> 3. always add it because I dont want in every change to go to the shitty coveralls.io website to regen it and get it and etc, and etc.

See how it is already done in other modules. You do NOT need to add the token to the Git repo, as coveralls now support Travis CI out-of-the-box. No tokens needed.

Posting the token unencrypted is a security hole, and can be exploited. See for example davidbau/seedrandom#17 and [proof of concept](https://coveralls.io/builds/1838552).

> templates, templates, templates. I must change them soon. Also they are the reason for the author and etc stuff.  I just forgot that.

Yes I understand. I am planning on create a boilerplates repo under the org to make it easier to create new modules.

**Comment by tunnckoCore** [comment]
> No tokens needed.

hm, thanks, good to know.

**Comment by ForbesLindesay** [comment]
As part of the www I was thinking of creating a not so we could have a button that anyone (within reason) could create a new repo with appropriate boilerplate set up and be given admin rights.

As for naming I'd much prefer css-parse but I can see why you went with css. The convention is to use the module name, but in this case that isn't very descriptive.

What I had in mind for rework was using rework and taking a list of plugins to do css to css transformation.

**Comment by ForbesLindesay** [comment]
For versioning, don't duplicate the version.  You already put that in the heading of the changelig anyway.  Look at github.com/jadejs/jade for an example of how the change log should look.

We may want to create tooling around change logs or an additional www page in the future so we should be careful to keep that consistent.

**Comment by tunnckoCore** [comment]
> What I had in mind for rework was using rework and taking a list of plugins to do css to css transformation.

cool. and seems it is better that I didn't get the `jstransformer-reworkcss` name :)

**Comment by tunnckoCore** [comment]
habits, bite me, lol

I was better you start with these things before any else.

**Comment by tunnckoCore** [comment]
Can I use different promise library?

**Comment by ForbesLindesay** [comment]
It should just be `jstransformer-rework` as that's the module name.  We don't generally append the output format to the name.

Also postcss should output the transformed css rather than an ast.  We could have a separate postcss-parser transform.

**Comment by tunnckoCore** [comment]
You're added to the npm, guys. :)

btw, about 
> I'll write a bot at some point to add all of the owners on GitHub as owners on npm :)

I called it `package-ownership` https://github.com/tunnckoCore/blankr/issues/23

**Comment by TimothyGu** [comment]
@tunnckoCore 
> I called it `package-ownership` tunnckoCore/blankr#23

BTW, the bot itself literally takes only [6 lines of Bash code](https://github.com/jstransformers/jstransformer/issues/1#issuecomment-74461500). Problem is we don't know where to **store** the owner information.

**Comment by tunnckoCore** [comment]
I try it, but not works for me on centos.

> Problem is we don't know where to store the owner information.

meta repository as in [regexps](https://github.com/regexps/meta), [regexps](https://github.com/datetime/meta)

**Comment by hemanth** [comment]
A big :+1: for a meta repository, it's proven to be very useful multiple number of times.

**Comment by TimothyGu** [comment]
^^ +1 too. Created: https://github.com/jstransformers/meta

**Comment by TimothyGu** [comment]
@tunnckoCore said:
> I try it, but not works for me on centos.

Yes, because that depends on the up-to-dateness of the ownership of the `jstransformer` package, which right now only has one owner.

**Comment by tunnckoCore** [comment]
`toml` and `ini` added to the list.

**Comment by tunnckoCore** [comment]
@ForbesLindesay feel free to change purpose of `postcss` and `css` transformers, your ideas seems better

**Comment by tunnckoCore** [comment]
:sparkles: toml :sparkles: done

**Comment by tunnckoCore** [comment]
https://github.com/Leonidas-from-XIV/node-xml2js - added to the list

**Comment by tunnckoCore** [comment]
:sparkles: toffee :sparkles: done
:sparkles: xml2js :sparkles: done
:sparkles: mini-handlebars :sparkles: done

:sparkles: j140 :sparkles: added, btw mega powerful for just 140bytes lib, but using `with`
:sparkles: octet :sparkles: added

:sparkles: [handlebars](https://github.com/tunnckoCore/jstransformer-handlebars) :sparkles: PR added more tests and `render` methods

**Comment by tunnckoCore** [comment]
:sparkles: [gray-matter](https://github.com/jonschlinkert/gray-matter) :sparkles: added

**Comment by tunnckoCore** [comment]
:sparkles: lodash :sparkles: added

**Comment by ForbesLindesay** [comment]
Don't forget to push your code before commenting here

**Comment by tunnckoCore** [comment]
@ForbesLindesay yea. With "added" I mean "added to the list" :)

btw, about template cruft, no problems I'll update all my libs in org as soon as I create basic project generator for jstransformers - workin on that now :)

**Comment by TimothyGu** [comment]
@tunnckoCore please add the new libraries to the "potential extras" instead of the main list. Also, you can try porting the ones from transformers first THEN adding extras.

**Comment by tunnckoCore** [comment]
> please add the new libraries to the "potential extras"

@TimothyGu sorry, done and okey.

**Comment by stoeffel** [comment]
I created a transformer for jsx. If you like I can pass it over to you guys.
https://github.com/stoeffel/jstransformer-jsx

**Comment by hemanth** [comment]
Nice @stoeffel.

Update: Sorted the list and looks like `jqtpl` is depreciated, so stroked it.

**Comment by tunnckoCore** [comment]
@jstransformers/owners btw, I reimplement the `rework` and `postcss` transforms to match @ForbesLindesay expectations and ideas - css to css transformation.
I thought the following wold be the best:
- jstransformer-rework - css to css transformation
- jstransformer-postcss - css to css transformation
- jstransformer-css - css to json ast, using `reworkcss/css` parser
- jstransformer-postcss-parser - css to json ast, using postcss

**Comment by tunnckoCore** [comment]
will commit them tomorrow :)

**Comment by ForbesLindesay** [comment]
@tunnckoCore That sounds ideal

**Comment by stoeffel** [comment]
I have moved `jstransformer-jsx` from `stoeffel/jstransformer-jsx` to `jstransformers/jstransformer-jsx`.

**Comment by tunnckoCore** [comment]
I'm back again :) All is done, going to normalize/update my other libs in org.

**Comment by RobLoach** [comment]
Thoughts on [jstransformer-es6-templates](https://github.com/RobLoach/jstransformer-es6-templates)? It's a bit hacky, so I'm not sure if it's something for `/jstransformers`.

**Comment by tunnckoCore** [comment]
:+1: I think for it before few days, but using https://github.com/medikoo/es6-template-strings instead.

**Comment by tunnckoCore** [comment]
@RobLoach seems to be better to use medikoo's package, its more up-to-date.

**Comment by RobLoach** [comment]
> I think for it before few days, but using https://github.com/medikoo/es6-template-strings instead.

Thanks! Good find.... Updated and moved to here:
https://github.com/jstransformers/jstransformer-es6-template-strings

**Comment by tunnckoCore** [comment]
@RobLoach see the commit comment :)

**Comment by RobLoach** [comment]
@stoeffel Used `generator-jstransformer` for [jstransformer-es6-template-strings](https://github.com/jstransformers/jstransformer-es6-template-strings), [jstransformer-whiskers](https://github.com/jstransformers/jstransformer-whiskers) and [jstransformer-styl](https://github.com/jstransformers/jstransformer-styl). It worked perfectly :+1: .

**Comment by tunnckoCore** [comment]
@RobLoach yep, but yeoman is too big and too shitty, same as gulp. lol

btw, should run `add-owners` for ur packages :)

**Comment by tunnckoCore** [comment]
:100: `jstransformer-absurd` :100:  added to the list and almost finished, it little tricky because not so node-friendly api.

**Comment by stoeffel** [comment]
@RobLoach nice :sunglasses:

**Comment by tunnckoCore** [comment]
hm.. both `coffeekup` and `coffeecup` looks very outdated and are similiar, so i think we should implement only one of them?

**Comment by tunnckoCore** [comment]
`coffeekup` - done

**Comment by tunnckoCore** [comment]
list is sorted again
added to the list
- autoprefixer built with postcss
- cssnext built with postcss
- doiuse built with postcss
- fest xml to html transformation
- gaikan
- rtlcss
- slm-lang
- resin

**Comment by ForbesLindesay** [comment]
I'm not sure about the explosion of postcss based transformers.  I feel like maybe we should be taking the approach of the `less` transformer and accepting a `plugins` option instead of having a jstransformer per plugin.  One very real downside of the approach we are taking at the moment is that a pipeline of postcss transformations could have very poor performance.

**Comment by tunnckoCore** [comment]
> a plugins option

Yea, we will. But they are almost separate transformation tools, commonly used and it will be just sugar of doing `install jstransformer-postcss, install cssnext, install autoprefixer` separately.

This dont have bad side.

> is that a pipeline of postcss transformations could have very poor performance.

And? This isn't jstransformer(s) problem.

**Comment by RobLoach** [comment]
:sparkles: https://github.com/jstransformers/jstransformer-browserify :sparkles: 

> Plugins

I think it should take an `options.plugins` parameter, and process it accordingly in preparing `.compile`/`.render`. Having to build a Transformer for each plugin is a lot of maintenance work for us, and limits the abilities of what the transformer can do.

As a side note, we'll need this plugins pattern for https://github.com/jstransformers/jstransformer-browserify too.

**Comment by RobLoach** [comment]
@jstransformers/owners First pass on https://github.com/jstransformers/jstransformer-cli .... Let's get discussions going on over in the issue queue there.

**Comment by tunnckoCore** [comment]
> Having to build a Transformer for each plugin is a lot of maintenance work for us, and limits the abilities of what the transformer can do.

i'll repeat again, there's no bad side of this. it not limit what `jstransformer` can/will do.

**Comment by ForbesLindesay** [comment]
@tunnckoCore The thing is that maintaining those is out of scope for jstransformers.  It is crucial to the success of any organisation that it remain focused.  There are three reasons this is really important:

1. There is another, much better way for us to support this, via a simple "plugins" option.  This is idiomatic of how jstransformers are generally expected to work (see jstransformer-less for example).
2. By forcing each plugin to be a separate jstransformer, we make some functionality impossible. For plugins that take `x` -> `y` rather than `x` -> `x` you can't always break things up in the way you want to.  Consider, for example, browserify transforms.  You have to give all the transforms you want to the same, single, browserify instance.  You simply cannot do it in multiple passes.
3. Doing multiple passes can create a massive performance bottleneck.  Say I want to use `cssnext` and `doiuse` from postcss: if I use the plugins system, it parses the css once, applies two transformations to the AST, then outputs that AST to a string.  If I use your approach, I have to parse the AST and then stringify it for each plugin I want to make use of.  That performance bottleneck is our problem, not the problem of postcss.

**Comment by tunnckoCore** [comment]
It seems you dont understand me correct. Im not against plugins option. The idea is to support separate jstransformers only for some of postcss plugins which walk their way to the future as separate tools. It would be more clean and lean to use just jstransformer-cssnext, no using plugins option for only one plugin.

Choosing to use separate jstransformers in this way, when we have support for both ways would be idiotism, yea. And this would be user's implementation/architecture design mistake, not our problem - we all have heads on our arms. I just won't support users that cant think, that dont have some principles and at least little basic knowledge about "what and how", that dont have logical/rational mind.

**Comment by tunnckoCore** [comment]
Its looks better
```js
var transformer = cssnext.renderFile('path/to/foo/bar.css', {})

// instead of
var transformer = postcss.renderFile('path/to/foo/bar.css', {plugins: [cssnext()]})
```

**Comment by tunnckoCore** [comment]
`resin` done, but i didn't notice that the `resin` package is out-of-date and they move to `topcoat-resin` and republish, soo yea shitty shits.

postcss and rework now support options.plugins.

**Comment by RobLoach** [comment]
-[ ] http://npm.im/Marko

**Comment by RobLoach** [comment]
@tunnckoCore found https://github.com/stylecow/stylecow

**Comment by tunnckoCore** [comment]
@RobLoach haha, you're good follower! :cat2:

**Comment by hemanth** [comment]
We still have few left in the potential extras list.

**Comment by RobLoach** [comment]
I've created a Label for this, and added each Transformer as an issue so that we can track them individually:
https://github.com/jstransformers/jstransformer/issues?q=is%3Aopen+is%3Aissue+label%3ATransformer

Great work, guys!

**Comment by ForbesLindesay** [comment]
:+1: awesome work.

Thanks so much for supporting this project everyone.  I'm so excited for how big this is becoming.
